services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ecommerce-orders
    volumes:
      - ecommerce_pg_data:/bitnami/postgresql

volumes:
  ecommerce_pg_data: